// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.humanos.infrastructure.BdServices;

#nullable disable

namespace api.humanos.infrastructure.Migrations
{
    [DbContext(typeof(HumanosDbContext))]
    [Migration("20240905151144_AddInitialMigration")]
    partial class AddInitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("api.humanos.domain.POCOS.Context.HumanosModel", b =>
                {
                    b.Property<int>("id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<double>("altura")
                        .HasColumnType("double")
                        .HasColumnName("altura");

                    b.Property<int>("edad")
                        .HasColumnType("int")
                        .HasColumnName("edad");

                    b.Property<string>("nombre")
                        .HasColumnType("string")
                        .HasColumnName("nombre");

                    b.Property<double>("peso")
                        .HasColumnType("double")
                        .HasColumnName("peso");

                    b.Property<string>("sexo")
                        .HasColumnType("string")
                        .HasColumnName("sexo");

                    b.HasKey("id")
                        .HasName("PK_User");

                    b.ToTable("Humanos", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
